const { Client } = require("pg");

// Load Next.js environment configuration
try {
  const { loadEnvConfig } = require("@next/env");
  loadEnvConfig(process.cwd());
} catch (e) {
  console.log("Next.js env loader not available, falling back to process.env directly.");
}

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  console.error("ERROR: DATABASE_URL environment variable is not defined in any env file or shell.");
  process.exit(1);
}

const papers = [
  {
    id: "attention",
    title: "Attention Is All You Need",
    authors: "Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan N. Gomez, Łukasz Kaiser, Illia Polosukhin",
    abstract: "The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely. Experiments on two machine translation tasks show these models to be superior in quality while being more parallelizable and requiring significantly less time to train.",
    publication: "Advances in Neural Information Processing Systems",
    conference: "NeurIPS 2017",
    journal: "CoRR",
    publication_date: "2017-06-12T00:00:00Z",
    year: 2017,
    research_area: "Natural Language Processing",
    category: "Attention",
    tags: ["Transformer", "Attention", "NMT", "SOTA"],
    keywords: ["Self-Attention", "Sequence transduction", "Transformer", "Translation"],
    tasks: ["Machine Translation", "Language Modeling", "Constituency Parsing"],
    methods: ["Self-Attention", "Multi-Head Attention", "Scaled Dot-Product Attention"],
    models: ["Transformer-Base", "Transformer-Big"],
    datasets: ["WMT 2014 English-to-German", "WMT 2014 English-to-French"],
    citations: 95342,
    paper_url: "https://arxiv.org/abs/1706.03762",
    github_url: "https://github.com/tensorflow/tensor2tensor",
    project_url: "https://arxiv.org/abs/1706.03762",
    pdf_url: "/papers/attention.pdf",
    thumbnail_url: "/thumbnails/attention.svg",
    pages: 15,
    file_size: "2.1 MB",
    doi: "10.48550/arXiv.1706.03762",
    framework: "TensorFlow",
    language: "Python",
    reading_time: "15 min",
    benchmarks: ["WMT2014 English-to-German", "WMT2014 English-to-French"],
    results: ["28.4 BLEU", "41.8 BLEU"],
    sota: "SOTA on WMT2014 English-to-German (28.4 BLEU) • WMT2014 English-to-French (41.8 BLEU)",
    github_stars: 12500,
    github_forks: 3100,
    github_issues: 94
  },
  {
    id: "bert",
    title: "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding",
    authors: "Jacob Devlin, Ming-Wei Chang, Kenton Lee, Kristina Toutanova",
    abstract: "We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers. Unlike recent language representation models, BERT is designed to pre-train deep bidirectional representations from unlabeled text by jointly conditioning on both left and right context in all layers. As a result, the pre-trained BERT model can be fine-tuned with just one additional output layer to create state-of-the-art models for a wide range of tasks, such as question answering and language inference, without substantial task-specific architecture modifications.",
    publication: "NAACL-HLT 2019",
    conference: "NAACL 2019",
    journal: "CoRR",
    publication_date: "2018-10-11T00:00:00Z",
    year: 2018,
    research_area: "Natural Language Processing",
    category: "Architecture",
    tags: ["BERT", "Pre-training", "Transformer", "Bidirectional"],
    keywords: ["Masked Language Model", "Pre-training", "Transformers", "NLP Representations"],
    tasks: ["Question Answering", "Sentiment Analysis", "Named Entity Recognition", "Natural Language Inference"],
    methods: ["Masked Language Modeling (MLM)", "Next Sentence Prediction (NSP)", "Fine-Tuning"],
    models: ["BERT-Base", "BERT-Large"],
    datasets: ["GLUE Benchmark", "SQuAD v1.1", "SQuAD v2.0"],
    citations: 85210,
    paper_url: "https://arxiv.org/abs/1810.04805",
    github_url: "https://github.com/google-research/bert",
    project_url: "https://arxiv.org/abs/1810.04805",
    pdf_url: "/papers/bert.pdf",
    thumbnail_url: "/thumbnails/bert.svg",
    pages: 16,
    file_size: "775 KB",
    doi: "10.48550/arXiv.1810.04805",
    framework: "TensorFlow / PyTorch",
    language: "Python",
    reading_time: "18 min",
    benchmarks: ["GLUE Score", "SQuAD 1.1 F1", "SQuAD 2.0 F1"],
    results: ["82.1%", "92.8", "83.1"],
    sota: "SOTA on GLUE Score (82.1%) • SQuAD 1.1 F1 (92.8) • SQuAD 2.0 F1 (83.1)",
    github_stars: 35400,
    github_forks: 9200,
    github_issues: 412
  },
  {
    id: "llama",
    title: "LLaMA: Open and Efficient Foundation Language Models",
    authors: "Hugo Touvron, Thibaut Lavril, Gautier Izacard, Xavier Martinet, Marie-Anne Lachaux, Timothée Lacroix, Baptiste Rozière, Naman Goyal, Eric Hambro, Faisal Azhar, Aurelien Rodriguez, Armand Joulin, Edouard Grave, Guillaume Lample",
    abstract: "We introduce LLaMA, a collection of foundation language models ranging from 7B to 65B parameters. We train our models on trillions of tokens, and show that it is possible to train state-of-the-art models using publicly available datasets exclusively, without resorting to proprietary and inaccessible datasets. In particular, LLaMA-13B outperforms GPT-3 (175B) on most benchmarks, and LLaMA-65B is competitive with the best models, such as Chinchilla-70B and PaLM-540B. We release all our models to the research community.",
    publication: "arXiv preprint",
    conference: "arXiv 2023",
    journal: "arXiv",
    publication_date: "2023-02-27T00:00:00Z",
    year: 2023,
    research_area: "Natural Language Processing",
    category: "Architecture",
    tags: ["LLM", "Open Source", "Autoregressive", "Transformer-Decoder"],
    keywords: ["LLaMA", "Decoder-only", "Instruction Finetuning", "Foundation Models"],
    tasks: ["Common Sense Reasoning", "Mathematical Reasoning", "Code Generation", "Trivia QA"],
    methods: ["Pre-normalization (RMSNorm)", "SwiGLU Activation", "Rotary Embeddings (RoPE)", "AdamW Optimization"],
    models: ["LLaMA-7B", "LLaMA-13B", "LLaMA-33B", "LLaMA-65B"],
    datasets: ["CommonCrawl", "C4", "GitHub", "Wikipedia", "Books", "ArXiv", "StackExchange"],
    citations: 8200,
    paper_url: "https://arxiv.org/abs/2302.13971",
    github_url: "https://github.com/facebookresearch/llama",
    project_url: "https://llama.meta.com",
    pdf_url: "/papers/llama.pdf",
    thumbnail_url: "/thumbnails/llama.svg",
    pages: 27,
    file_size: "726 KB",
    doi: "10.48550/arXiv.2302.13971",
    framework: "PyTorch",
    language: "Python",
    reading_time: "25 min",
    benchmarks: ["MMLU (5-shot)", "GSM8k (8-shot)", "HumanEval (0-shot)"],
    results: ["63.4%", "50.9%", "23.7%"],
    sota: "SOTA on LLaMA-65B MMLU (63.4%) • GSM8k (50.9%) • HumanEval (23.7%)",
    github_stars: 52000,
    github_forks: 8900,
    github_issues: 185
  },
  {
    id: "gpt4",
    title: "GPT-4 Technical Report",
    authors: "OpenAI",
    abstract: "We report the development of GPT-4, a large-scale, multimodal model which can accept image and text inputs and produce text outputs. While less capable than humans in many real-world scenarios, GPT-4 exhibits human-level performance on various professional and academic benchmarks, including passing a simulated bar exam with a score around the top 10% of test takers. GPT-4 is a Transformer-style model pre-trained to predict the next token in a document. The post-training alignment process results in improved performance on measures of factuality and adherence to desired behavior.",
    publication: "arXiv preprint",
    conference: "arXiv 2023",
    journal: "arXiv",
    publication_date: "2023-03-15T00:00:00Z",
    year: 2023,
    research_area: "Natural Language Processing",
    category: "Architecture",
    tags: ["Multimodal", "RLHF", "Closed-Source", "LLM"],
    keywords: ["GPT-4", "Multimodal Large Language Model", "Reinforcement Learning from Human Feedback"],
    tasks: ["Professional Exams", "Visual QA", "Reasoning", "Coding"],
    methods: ["Reinforcement Learning from Human Feedback (RLHF)", "Supervised Fine-Tuning (SFT)", "Predictable Scaling"],
    models: ["GPT-4-Base", "GPT-4-Turbo"],
    datasets: ["Proprietary Multimodal Datasets"],
    citations: 12400,
    paper_url: "https://arxiv.org/abs/2303.08774",
    github_url: "https://github.com/openai/gpt-4",
    project_url: "https://openai.com/research/gpt-4",
    pdf_url: "/papers/gpt4.pdf",
    thumbnail_url: "/thumbnails/gpt4.svg",
    pages: 100,
    file_size: "5.2 MB",
    doi: "10.48550/arXiv.2303.08774",
    framework: "Proprietary",
    language: "C++ / Python",
    reading_time: "45 min",
    benchmarks: ["Uniform Bar Exam", "LSAT Score", "MMLU (no-shot)"],
    results: ["90th percentile", "88th percentile", "86.4%"],
    sota: "SOTA on simulated Bar Exam (90th pct) • MMLU (86.4% Accuracy)",
    github_stars: 4800,
    github_forks: 950,
    github_issues: 55
  },
  {
    id: "gpt3",
    title: "Language Models are Few-Shot Learners",
    authors: "Tom B. Brown, Benjamin Mann, Nick Ryder, Melanie Subbiah, Jared Kaplan, Prafulla Dhariwal, Arvind Neelakantan, Pranav Shyam, Girish Sastry, Amanda Askell, Sandhini Agarwal, Ariel Herbert-Voss, Gretchen Krueger, Tom Henighan, Rewon Child, Aditya Ramesh, Daniel M. Ziegler, Jeffrey Wu, Clemens Winter, Christopher Hesse, Mark Chen, Eric Sigler, Mateusz Litwin, Scott Gray, Benjamin Chess, Jack Clark, Christopher Berner, Sam McCandlish, Alec Radford, Ilya Sutskever, Dario Amodei",
    abstract: "We show that scaling up language models greatly improves task-agnostic, few-shot performance, sometimes even reaching competitiveness with prior state-of-the-art fine-tuning approaches. Specifically, we train GPT-3, an autoregressive language model with 175 billion parameters, 10x more than any previous non-sparse language model, and evaluate its performance in the few-shot setting. For all tasks, GPT-3 is applied without any gradient updates or fine-tuning, with tasks and few-shot demonstrations specified purely via text interaction with the model.",
    publication: "Advances in Neural Information Processing Systems",
    conference: "NeurIPS 2020",
    journal: "CoRR",
    publication_date: "2020-05-28T00:00:00Z",
    year: 2020,
    research_area: "Natural Language Processing",
    category: "Architecture",
    tags: ["GPT-3", "Few-Shot", "Autoregressive LLM", "In-Context Learning"],
    keywords: ["Generative Pre-trained Transformer 3", "Few-shot learning", "Zero-shot learning"],
    tasks: ["Few-Shot Reasoning", "Text Generation", "Translation", "Common Sense QA"],
    methods: ["In-Context Learning", "Autoregressive Pre-training", "Generative Decoding"],
    models: ["GPT-3 175B"],
    datasets: ["CommonCrawl (filtered)", "WebText2", "Books1", "Books2", "Wikipedia"],
    citations: 25410,
    paper_url: "https://arxiv.org/abs/2005.14165",
    github_url: "https://github.com/openai/gpt-3",
    project_url: "https://openai.com/research/gpt-3",
    pdf_url: "/papers/gpt3.pdf",
    thumbnail_url: "/thumbnails/gpt3.svg",
    pages: 75,
    file_size: "6.8 MB",
    doi: "10.48550/arXiv.2005.14165",
    framework: "Proprietary",
    language: "Python",
    reading_time: "35 min",
    benchmarks: ["SuperGLUE (Few-Shot)", "TriviaQA (Few-Shot)", "LAMBADA (Zero-Shot)"],
    results: ["71.8", "76.2%", "76.2%"],
    sota: "SOTA on LAMBADA Accuracy (76.2%) • TriviaQA Few-Shot (76.2%)",
    github_stars: 8200,
    github_forks: 1800,
    github_issues: 76
  },
  {
    id: "t5",
    title: "Exploring the Limits of Transfer Learning with a Unified Text-to-Text Transformer",
    authors: "Colin Raffel, Noam Shazeer, Adam Roberts, Katherine Lee, Sharan Narang, Michael Matena, Yanqi Zhou, Wei Li, Peter J. Liu",
    abstract: "Deep learning efficacy depends heavily on transfer learning: pre-training a model on a data-rich task before fine-tuning on downstream tasks. We introduce a unified framework that casts all text-based language problems into a text-to-text format. We systematically study transfer learning techniques and train a model, the Text-to-Text Transfer Transformer (T5), that achieves state-of-the-art results on GLUE, SuperGLUE, SQuAD, and CNN/Daily Mail. We release our dataset, the Colossal Clean Crawled Corpus (C4), and pre-trained models.",
    publication: "Journal of Machine Learning Research",
    conference: "JMLR 2020",
    journal: "JMLR",
    publication_date: "2019-10-23T00:00:00Z",
    year: 2020,
    research_area: "Natural Language Processing",
    category: "Training",
    tags: ["T5", "Text-to-Text", "C4 Dataset", "Encoder-Decoder"],
    keywords: ["Transfer Learning", "Unified Framework", "Colossal Clean Crawled Corpus", "Encoder-Decoder Transformer"],
    tasks: ["Text Summarization", "Question Answering", "Sentence Similarity", "Grammar Correction"],
    methods: ["Text-to-Text Unified Interface", "Multi-Task Pre-training", "Relative Position Buckets"],
    models: ["T5-Small", "T5-Base", "T5-Large", "T5-3B", "T5-11B"],
    datasets: ["C4 (Colossal Clean Crawled Corpus)", "GLUE", "SuperGLUE", "CNN/Daily Mail"],
    citations: 18450,
    paper_url: "https://arxiv.org/abs/1910.10683",
    github_url: "https://github.com/google-research/text-to-text-transfer-transformer",
    project_url: "https://arxiv.org/abs/1910.10683",
    pdf_url: "/papers/t5.pdf",
    thumbnail_url: "/thumbnails/t5.svg",
    pages: 67,
    file_size: "1.2 MB",
    doi: "10.48550/arXiv.1910.10683",
    framework: "TensorFlow / Mesh-TensorFlow",
    language: "Python / Mesh-TF",
    reading_time: "20 min",
    benchmarks: ["SuperGLUE Score", "GLUE Score", "CNN/Daily Mail R-L"],
    results: ["88.9", "90.3", "30.38"],
    sota: "SOTA on SuperGLUE (88.9) • GLUE (90.3) • CNN/Daily Mail ROUGE-L (30.38)",
    github_stars: 6400,
    github_forks: 1400,
    github_issues: 110
  },
  {
    id: "roberta",
    title: "RoBERTa: A Robustly Optimized BERT Pretraining Approach",
    authors: "Yinhan Liu, Myle Ott, Naman Goyal, Jingfei Du, Mandar Joshi, Danqi Chen, Omer Levy, Mike Lewis, Luke Zettlemoyer, Veselin Stoyanov",
    abstract: "Language model pretraining has led to significant performance gains but careful comparisons between different approaches can be challenging. We present a replication study of BERT pretraining that carefully measures the impact of key hyperparameters and training data size. We find that BERT was significantly undertrained, and can match or exceed the performance of every post-BERT method published since. Our best model, RoBERTa, state-of-the-art results on GLUE, LAMA and SQuAD.",
    publication: "arXiv preprint",
    conference: "arXiv 2019",
    journal: "arXiv",
    publication_date: "2019-07-26T00:00:00Z",
    year: 2019,
    research_area: "Natural Language Processing",
    category: "Optimization",
    tags: ["RoBERTa", "Optimization", "Pretraining Hyperparameters", "BERT Replicability"],
    keywords: ["Dynamic Masking", "BPE Vocab", "Large Batch Pretraining"],
    tasks: ["Text Classification", "Natural Language Inference", "Reading Comprehension"],
    methods: ["Dynamic Masking", "Training without NSP", "Large Mini-Batches", "Byte-Level BPE"],
    models: ["RoBERTa-Base", "RoBERTa-Large"],
    datasets: ["BookCorpus", "English Wikipedia", "CC-News", "OpenWebText", "Stories"],
    citations: 22100,
    paper_url: "https://arxiv.org/abs/1907.11692",
    github_url: "https://github.com/facebookresearch/fairseq",
    project_url: "https://github.com/facebookresearch/fairseq/tree/main/examples/roberta",
    pdf_url: "/papers/roberta.pdf",
    thumbnail_url: "/thumbnails/roberta.svg",
    pages: 13,
    file_size: "210 KB",
    doi: "10.48550/arXiv.1907.11692",
    framework: "PyTorch (Fairseq)",
    language: "Python",
    reading_time: "14 min",
    benchmarks: ["GLUE Avg Score", "SQuAD 2.0 F1", "MNLI Accuracy"],
    results: ["88.5", "89.8", "90.2%"],
    sota: "SOTA on GLUE (88.5) • SQuAD 2.0 F1 (89.8) • MNLI-m (90.2%)",
    github_stars: 28500,
    github_forks: 6400,
    github_issues: 225
  },
  {
    id: "palm",
    title: "PaLM: Scaling Language Modeling with Pathways",
    authors: "Aakanksha Chowdhery, Sharan Narang, Jacob Devlin, Maarten Bosma, Gaurav Mishra, Adam Roberts, Paul Barham, Hyung Won Chung, Charles Sutton, Sebastian Gehrmann, Parker Schuh, Kensen Shi, Sasha Tsvyashchenko, Joshua Maynez, Abhishek Rao, Parker Barnes, Yi Tay, Noam Shazeer, Vinodkumar Prabhakaran, Emily Reif, Nan Du, Ben Hutchinson, Reiner Pope, James Bradbury, Jacob Austin, Michael Isard, Guy Gur-Ari, Pengcheng Yin, Toju Duke, Anselm Levskaya, Sanjay Ghemawat, Sunipa Dev, Henryk Michalewski, Xavier Garcia, Vedant Misra, Kevin Robinson, Liam Fedus, Denny Zhou, Daphne Ippolito, David Luan, Hyeontaek Lim, Barret Zoph, Alexander Spiridonov, Ryan Sepassi, David Dohan, Shivani Agrawal, Mark Omernick, Andrew M. Dai, Thanumalayan Sankaranarayana Pillai, Marie Pellat, Aitor Lewkowycz, Erica Moreira, Rewon Child, Oleksandr Polozov, Katherine Lee, Zongwei Zhou, Xuezhi Wang, Brennan Saeta, Mark Diaz, Orhan Firat, Michele Catasta, Jason Wei, Kathy Meier-Hellstern, Douglas Eck, Jeff Dean",
    abstract: "We introduce Pathways Language Model (PaLM), a 540-billion parameter, dense decoder-only Transformer model trained on 6144 TPU v4 chips using the Pathways system. PaLM demonstrates the first large-scale multi-task training on distributed TPU pods, achieving breakthrough performance on hundreds of language, reasoning, and coding tasks, outperforming state-of-the-art models on a majority of benchmarks.",
    publication: "Journal of Machine Learning Research",
    conference: "JMLR 2022",
    journal: "JMLR",
    publication_date: "2022-04-05T00:00:00Z",
    year: 2022,
    research_area: "Natural Language Processing",
    category: "Architecture",
    tags: ["Pathways", "PaLM", "tpuv4", "Large-Scale Parallelism"],
    keywords: ["Pathways system", "TPU pods", "Decoder-only scaling", "Multi-dataset modeling"],
    tasks: ["Logic Puzzles", "Arithmetics", "Translation", "Code Synthesis"],
    methods: ["Pathways Execution Engine", "Parallel Attention & Feed-Forward", "SwiGLU Activation", "Multi-Query Attention"],
    models: ["PaLM 8B", "PaLM 62B", "PaLM 540B"],
    datasets: ["Social Media Conversations", "Multilingual Web Pages", "Books", "GitHub", "Wikipedia"],
    citations: 4500,
    paper_url: "https://arxiv.org/abs/2204.02311",
    github_url: "https://github.com/google-research/pathways-language-model",
    project_url: "https://arxiv.org/abs/2204.02311",
    pdf_url: "/papers/palm.pdf",
    thumbnail_url: "/thumbnails/palm.svg",
    pages: 88,
    file_size: "2.7 MB",
    doi: "10.48550/arXiv.2204.02311",
    framework: "JAX / Pathways",
    language: "Python",
    reading_time: "40 min",
    benchmarks: ["BIG-bench (few-shot)", "GSM8k (few-shot)", "HumanEval (0-shot)"],
    results: ["62.8%", "58.8%", "26.2%"],
    sota: "SOTA on GSM8k 5-shot CoT (58.8%) • BIG-bench 5-shot (62.8%)",
    github_stars: 4200,
    github_forks: 580,
    github_issues: 22
  },
  {
    id: "opt",
    title: "OPT: Open Pre-trained Transformer Language Models",
    authors: "Susan Zhang, Stephen Roller, Naman Goyal, Mikel Artetxe, Moya Chen, Shuohui Chen, Christopher Dewan, Mona Diab, Xian Li, Xi Victoria Lin, Todor Mihaylov, Myle Ott, Sam Shleifer, Aurélie Rodriguez, Naman Goyal, Armand Joulin, Edouard Grave, Guillaume Lample",
    abstract: "Large language models, which have shown capabilities in few-shot learning, have been difficult to replicate due to their computational requirements. We present Open Pre-trained Transformers (OPT), a suite of decoder-only pre-trained transformers ranging from 125M to 175B parameters, which we share openly with the research community. We detail our training process, settings, and hardware issues, showing that OPT-175B is comparable to GPT-3 while requiring only a fraction of the carbon footprint to train.",
    publication: "arXiv preprint",
    conference: "arXiv 2022",
    journal: "arXiv",
    publication_date: "2022-05-03T00:00:00Z",
    year: 2022,
    research_area: "Natural Language Processing",
    category: "Architecture",
    tags: ["OPT", "Meta AI", "Open-Source LLM", "Decoder-Only"],
    keywords: ["Open Pre-trained Transformers", "Carbon Footprint Optimization", "Replicability Study"],
    tasks: ["Prompting Analysis", "Bias Evaluation", "Hate Speech Detection", "Few-Shot Classification"],
    methods: ["Weight Initialization (Megatron-LM style)", "Dynamic Learning Rate Scheduler", "AdamW"],
    models: ["OPT-125M", "OPT-350M", "OPT-1.3B", "OPT-2.7B", "OPT-6.7B", "OPT-13B", "OPT-30B", "OPT-66B", "OPT-175B"],
    datasets: ["BookCorpus", "Wikipedia", "CC-Stories", "The Pile (subset)", "Pushshift.io Reddit"],
    citations: 3100,
    paper_url: "https://arxiv.org/abs/2205.01068",
    github_url: "https://github.com/facebookresearch/metaseq",
    project_url: "https://github.com/facebookresearch/metaseq/tree/main/projects/OPT",
    pdf_url: "/papers/opt.pdf",
    thumbnail_url: "/thumbnails/opt.svg",
    pages: 35,
    file_size: "1.8 MB",
    doi: "10.48550/arXiv.2205.01068",
    framework: "PyTorch / Metaseq",
    language: "Python",
    reading_time: "22 min",
    benchmarks: ["Hate Speech Accuracy", "Zero-Shot Winograd", "Zero-Shot PIQA"],
    results: ["62.4%", "68.2%", "73.9%"],
    sota: "Competitive with GPT-3 on Zero-Shot Winograd (68.2%) • PIQA (73.9%)",
    github_stars: 6700,
    github_forks: 1100,
    github_issues: 124
  },
  {
    id: "flant5",
    title: "Flan-T5: Scaling Instruction-Finetuned Language Models",
    authors: "Hyung Won Chung, Le Hou, Shayne Longpre, Barret Zoph, Yi Tay, William Fedus, Eric Li, Hung-Tuo Zhou, Diyi Yang, Greg Ondrejka, Jeff Dean",
    abstract: "Instruction finetuning enables language models to respond to instructions and general tasks. We study the scaling of instruction finetuning on three aspects: number of tasks, model size, and task diversity. We train Flan-T5, an instruction-finetuned version of T5, and show that it outperforms the base models by large margins on reasoning, math, and code tasks, even in zero-shot and few-shot settings.",
    publication: "arXiv preprint",
    conference: "arXiv 2022",
    journal: "arXiv",
    publication_date: "2022-10-20T00:00:00Z",
    year: 2022,
    research_area: "Natural Language Processing",
    category: "Training",
    tags: ["Instruction-Finetuning", "Flan", "T5", "Google AI"],
    keywords: ["Flan-T5", "Instruction tuning scaling", "Task generalization", "Chain-of-thought fine-tuning"],
    tasks: ["Instruction Following", "Math Word Problems", "Multi-step Reasoning", "Code Completion"],
    methods: ["Instruction Tuning", "Chain-of-Thought Finetuning", "Multi-Task Fine-Tuning"],
    models: ["Flan-T5-Small", "Flan-T5-Base", "Flan-T5-Large", "Flan-T5-XL", "Flan-T5-XXL"],
    datasets: ["Muffin (80 tasks)", "T0-SF (55 tasks)", "NIV2 (1500+ tasks)", "Chain-of-Thought (9 tasks)"],
    citations: 3800,
    paper_url: "https://arxiv.org/abs/2210.11416",
    github_url: "https://github.com/google-research/t5x",
    project_url: "https://github.com/google-research/t5x",
    pdf_url: "/papers/flant5.pdf",
    thumbnail_url: "/thumbnails/flant5.svg",
    pages: 53,
    file_size: "1.6 MB",
    doi: "10.48550/arXiv.2210.11416",
    framework: "JAX / T5X",
    language: "Python",
    reading_time: "23 min",
    benchmarks: ["MMLU (Few-Shot CoT)", "MATH Benchmark", "GSM8k Accuracy"],
    results: ["55.1%", "12.4%", "44.8%"],
    sota: "SOTA on Flan-T5-XXL MMLU Few-Shot (55.1%) • GSM8k Accuracy (44.8%)",
    github_stars: 5400,
    github_forks: 880,
    github_issues: 49
  }
];

async function seed() {
  console.log("Connecting to PostgreSQL...");
  try {
    const url = new URL(connectionString);
    console.log(`Database host: ${url.hostname}`);
    console.log(`Database name: ${url.pathname.substring(1)}`);
    console.log(`Username: ${url.username}`);
  } catch (e) {
    console.warn("Could not parse connection string for logging.");
  }

  const client = new Client({
    connectionString,
    ssl: {
      rejectUnauthorized: false,
    },
  });
  
  try {
    await client.connect();
    console.log("Connected successfully. Initializing database schema...");
    
    // 1. Drop existing table if exists
    await client.query(`DROP TABLE IF EXISTS papers CASCADE;`);
    console.log("Dropped table 'papers' if it existed.");
    
    // 2. Create the papers table with the clean schema
    await client.query(`
      CREATE TABLE papers (
        id VARCHAR(255) PRIMARY KEY,
        title TEXT NOT NULL,
        authors TEXT NOT NULL,
        abstract TEXT,
        publication TEXT,
        conference TEXT,
        journal TEXT,
        publication_date TIMESTAMP WITH TIME ZONE,
        year INTEGER,
        research_area VARCHAR(255),
        category VARCHAR(255),
        tags TEXT[] DEFAULT '{}'::TEXT[],
        keywords TEXT[] DEFAULT '{}'::TEXT[],
        tasks TEXT[] DEFAULT '{}'::TEXT[],
        methods TEXT[] DEFAULT '{}'::TEXT[],
        models TEXT[] DEFAULT '{}'::TEXT[],
        datasets TEXT[] DEFAULT '{}'::TEXT[],
        citations INTEGER DEFAULT 0,
        paper_url TEXT,
        github_url TEXT,
        project_url TEXT,
        pdf_url TEXT,
        thumbnail_url TEXT,
        pages INTEGER DEFAULT 0,
        file_size VARCHAR(50),
        doi VARCHAR(255),
        framework VARCHAR(100),
        language VARCHAR(100),
        reading_time VARCHAR(50),
        benchmarks TEXT[] DEFAULT '{}'::TEXT[],
        results TEXT[] DEFAULT '{}'::TEXT[],
        sota TEXT,
        github_stars INTEGER DEFAULT 0,
        github_forks INTEGER DEFAULT 0,
        github_issues INTEGER DEFAULT 0
      );
    `);
    console.log("Created table 'papers'.");

    // 3. Insert each paper
    const insertQuery = `
      INSERT INTO papers (
        id, title, authors, abstract, publication, conference, journal,
        publication_date, year, research_area, category, tags, keywords,
        tasks, methods, models, datasets, citations, paper_url, github_url,
        project_url, pdf_url, thumbnail_url, pages, file_size, doi,
        framework, language, reading_time, benchmarks, results, sota,
        github_stars, github_forks, github_issues
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
        $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26,
        $27, $28, $29, $30, $31, $32, $33, $34, $35
      );
    `;

    for (const paper of papers) {
      console.log(`Inserting paper: ${paper.title} (${paper.id})...`);
      await client.query(insertQuery, [
        paper.id,
        paper.title,
        paper.authors,
        paper.abstract,
        paper.publication,
        paper.conference,
        paper.journal,
        paper.publication_date,
        paper.year,
        paper.research_area,
        paper.category,
        paper.tags,
        paper.keywords,
        paper.tasks,
        paper.methods,
        paper.models,
        paper.datasets,
        paper.citations,
        paper.paper_url,
        paper.github_url,
        paper.project_url,
        paper.pdf_url,
        paper.thumbnail_url,
        paper.pages,
        paper.file_size,
        paper.doi,
        paper.framework,
        paper.language,
        paper.reading_time,
        paper.benchmarks,
        paper.results,
        paper.sota,
        paper.github_stars,
        paper.github_forks,
        paper.github_issues
      ]);
    }
    
    console.log("All papers successfully seeded!");
  } catch (err) {
    console.error("Error during database seeding:", err);
  } finally {
    await client.end();
    console.log("Disconnected from PostgreSQL.");
  }
}

seed();
